[package]
name = "image-a-star"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.8", features = ["derive"] }
image = "0.25.1"
itertools = "0.13.0"
priority-queue = "2.0.3"
promptly = "0.3.1"
rand = "0.8.5"
